server {
  listen 8090;

  location /newrelic/ {
      proxy_pass          https://mcp.newrelic.com/mcp/;
      proxy_set_header    Api-Key "${NR_API_KEY}";
      proxy_set_header    Host mcp.newrelic.com;
      proxy_set_header    Accept "application/json, text/event-stream";
      proxy_set_header    Content-Type "application/json";
      proxy_ssl_server_name on;
      proxy_http_version  1.1;
      proxy_set_header    Connection "";
      proxy_buffering     off;
      proxy_cache         off;
      proxy_read_timeout  300s;
      chunked_transfer_encoding on;
  }

  location /metabase/ {
    proxy_pass          http://mcp-metabase:3200/mcp/;
    proxy_set_header    Accept "application/json, text/event-stream";
    proxy_http_version  1.1;
    proxy_set_header    Connection "";
    proxy_buffering     off;
    proxy_cache         off;
    proxy_read_timeout  300s;
    chunked_transfer_encoding on;
  }
}